version: "3.9"

services:
  Database:
    container_name: DatabaseService
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - bot_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot_network
    restart: unless-stopped

  Bot:
    container_name: BotService
    image: scheduler_tgbot
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      BOT_TOKEN: "${BOT_TOKEN}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    networks:
      - bot_network
    restart: unless-stopped

volumes:
  bot_volume:

networks:
  bot_network:
    driver: bridge
